AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for EventBridge rule 'demo'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "SNS Topic Configuration"
        Parameters:
          - SNSName
          - SNSProtocol
          - SNSEndpoint
      -
        Label:
          default: "EventBridge Configuration"
        Parameters:
          - EventRuleName
          - APICallName
    ParameterLabels:
      SNSName:
        default: "SNS Topic Name:"
      SNSProtocol:
        default: "SNS Protocol:"
      SNSEndpoint:
        default: "SNS Endpoint (as per SNS Protocol):"
      EventRuleName:
        default: "Eventbridge Rule Name:"
      APICallName:
        default: "CTrail Event Name/API Call:"
Parameters:
  SNSName:
    Type: String
  SNSProtocol:
    Type: String
    Default: email
    AllowedValues:
      - http
      - https
      - email
      - email-json
      - sms
      - sqs
      - application
      - lambda
  SNSEndpoint:
    Type: String
  EventRuleName:
    Type: String
  APICallName:
    Type: String
    Default: ReplicateImage
Resources:
  EventRule0:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
          - aws.ecr
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - ecr.amazonaws.com
          eventName:
            - !Ref APICallName
          errorCode:
            - exists: true
      Name: !Ref EventRuleName
      State: ENABLED
      Targets:
        - Id: !Sub "Id-${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"
          Arn: !Ref MySNSTopic
          InputTransformer:
            InputPathsMap:
              Error_Code: $.detail.errorCode
              Error_Message: $.detail.errorMessage
              Event_Name: $.detail.eventName
              Region: $.region
              Time: $.time
            InputTemplate: >-
              "Good Day User, This is to notify that '<Event_Name>' is failed in
              '<Region>' with '<Error_Code>' with message: '<Error_Message>'.
              This activity happened on '<Time>'"
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: !Ref SNSProtocol
          Endpoint: !Ref SNSEndpoint
      TopicName: !Ref SNSName